"""Update for date  migration

Revision ID: c71c7f2effea
Revises: 1b37dfb1fec3
Create Date: 2025-01-25 14:15:49.702173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71c7f2effea'
down_revision: Union[str, None] = '1b37dfb1fec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_day', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('order_month', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('order_year', sa.Integer(), nullable=True))
    op.drop_index('idx_user_order_date', table_name='orders')
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index('idx_user_order_date', 'orders', ['user_id', 'order_date'], unique=False)
    op.drop_column('orders', 'order_year')
    op.drop_column('orders', 'order_month')
    op.drop_column('orders', 'order_day')
    # ### end Alembic commands ###
